#!/bin/bash
#
#

echo " "
echo " "
echo " "
echo " "
echo "Runs ADE using a config-file 'aderc.cpm' that specifies"
echo " bootdisk floppy 'adv_cpm120_wm.nsi'"
echo "                 (Advantage CP/M Vers 1.2.0)"
echo "  and a 10 megabyte hard drive 'cm10ex.nhd' which contains  eight"
echo "  CP/M virtual disks 'CPMA', 'CPMB', up to  'CPMH' each 1 megabyte,"
echo "  the boot floppy is configured as 'I:' and second floppy is 'J:'"
echo " "
echo "         F1 is the Help-Key within the ADE Emulator."
echo " "

#comment out next 2 lines below to go straight through without pause
echo -n " Hit 'Return' to continue, 'Control-C' to stop.  "
read ANS


echo " "
echo " "
echo "             ADE initiated ......"



./ade -c aderc.cpm
