##### Initial Configuration File for North Star ADE Emulator (c) 240213
#####
##### Avoid Editing This File Manually. Any Changes You Make May
##### Be Automatically Overwritten at Any Time.
 
hdd           /usr/local/share/advantage/disks/ADV_SG5A.NHD 
fd1           /usr/local/share/advantage/disks/CPMBASIC_120A1.NSI
fd2           
disk_dir      /usr/local/share/advantage/disks/
debug_level   0000
break_addr    0000
break_on      off
trap_addr     FFFE
trap_on       off
hd_delay      off
capslock      off
cursor_lock   off
log           /usr/local/share/advantage/xlog
screenlog     /usr/local/share/advantage/screenlog
slot_hdc      6
slot_sio      2
slot_pio      1
sio_in        
sio_out       
pio_in         
pio_out        
