1 REM THIS IS A SHORT BASIC PROGRAM TO
2 REM TEST FOR CORRECT OPERATION OF ASCII
3 REM FILE INPUT IN PLACE OF THE USUAL
4 REM KEYBOARD OPERATION
5 REM SEE 'AREAD' MENU-ITEM
6 REM *********************************
10 FOR X = 1 to 10
20 Y=X+20
30 PRINT Y
40 NEXT X
